# Generated by Django 4.2 on 2025-01-21 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('B', 'Confort'), ('A', 'Organizacion'), ('H', 'Hool/Entrada')], max_length=30)),
                ('materials', models.CharField(choices=[('B', 'Bambu'), ('E', 'Eco-plasticos'), ('C', 'Corcho'), ('LO', 'Lino Orgonico'), ('FC', 'Fibras de Coco'), ('M', 'Madera Sostenible')], max_length=30)),
                ('styles', models.CharField(choices=[('S', 'Sostenibles'), ('I', 'Industrial'), ('MU', 'Multifuncionales'), ('M', 'Minimalista')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('dni', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('fruniture', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mueblesemae.mueble')),
            ],
        ),
    ]
