# Generated by Django 4.2 on 2025-02-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('dni', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('material', models.CharField(choices=[('M', 'Madera Sostenible'), ('B', 'Bambú'), ('E', 'Eco-plásticos'), ('C', 'Corcho'), ('L', 'Lino Orgánico'), ('F', 'Fibras de Coco')], max_length=30)),
                ('style', models.CharField(choices=[('M', 'Minimalista'), ('M', 'Multifuncionales'), ('S', 'Sostenibles'), ('I', 'Industrial')], max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('picture', models.ImageField(upload_to='muebles_images')),
                ('type', models.CharField(choices=[('O', 'Organización'), ('H', 'Hool'), ('C', 'Confort')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mueblesemae.cliente')),
                ('muebles', models.ManyToManyField(to='mueblesemae.mueble')),
            ],
        ),
    ]
