# Generated by Django 4.2 on 2025-01-23 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('B', 'Confort'), ('H', 'Hool/Entrada'), ('A', 'Organizacion')], max_length=30)),
                ('materials', models.CharField(choices=[('B', 'Bambu'), ('LO', 'Lino Orgonico'), ('E', 'Eco-plasticos'), ('M', 'Madera Sostenible'), ('C', 'Corcho'), ('FC', 'Fibras de Coco')], max_length=30)),
                ('styles', models.CharField(choices=[('M', 'Minimalista'), ('S', 'Sostenibles'), ('MU', 'Multifuncionales'), ('I', 'Industrial')], max_length=30)),
                ('picture', models.ImageField(upload_to='muebles_images')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('dni', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mueblesemae.mueble')),
            ],
        ),
    ]
