# Generated by Django 4.2 on 2025-02-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
    ]
