# Generated by Django 4.2 on 2025-01-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fruniture',
            new_name='furniture',
        ),
        migrations.AlterField(
            model_name='mueble',
            name='materials',
            field=models.CharField(choices=[('M', 'Madera Sostenible'), ('FC', 'Fibras de Coco'), ('C', 'Corcho'), ('LO', 'Lino Orgonico'), ('B', 'Bambu'), ('E', 'Eco-plasticos')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='styles',
            field=models.CharField(choices=[('I', 'Industrial'), ('M', 'Minimalista'), ('MU', 'Multifuncionales'), ('S', 'Sostenibles')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='type',
            field=models.CharField(choices=[('H', 'Hool/Entrada'), ('B', 'Confort'), ('A', 'Organizacion')], max_length=30),
        ),
    ]
