# Generated by Django 4.2 on 2025-01-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='materials',
            field=models.CharField(choices=[('LO', 'Lino Orgonico'), ('B', 'Bambu'), ('C', 'Corcho'), ('E', 'Eco-plasticos'), ('M', 'Madera Sostenible'), ('FC', 'Fibras de Coco')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='name',
            field=models.CharField(choices=[('B', 'Cama'), ('S', 'Sala de Estar'), ('A', 'Armario')], max_length=15),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='styles',
            field=models.CharField(choices=[('M', 'Minimalista'), ('I', 'Industrial'), ('S', 'Sostenibles'), ('MU', 'Multifuncionales')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='type',
            field=models.CharField(choices=[('A', 'Organizacion'), ('B', 'Confort'), ('H', 'Hool/Entrada')], max_length=30),
        ),
    ]
