# Generated by Django 4.2 on 2025-02-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
