# Generated by Django 4.2 on 2025-02-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
