# Generated by Django 4.2 on 2025-01-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='material',
            field=models.CharField(choices=[('M', 'Madera Sostenible'), ('B', 'Bambu'), ('E', 'Eco-plasticos'), ('C', 'Corcho'), ('L', 'Lino Orgonico'), ('F', 'Fibras de Coco')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='style',
            field=models.CharField(choices=[('M', 'Minimalista'), ('M', 'Multifuncionales'), ('S', 'Sostenibles'), ('I', 'Industrial')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tipo_mueble',
            name='type',
            field=models.CharField(choices=[('O', 'Organizacion'), ('H', 'Hool'), ('C', 'Confort')], max_length=30),
        ),
    ]
