# Generated by Django 4.2 on 2025-01-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0002_alter_mueble_materials_alter_mueble_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='materials',
            field=models.CharField(choices=[('M', 'Madera Sostenible'), ('C', 'Corcho'), ('E', 'Eco-plasticos'), ('LO', 'Lino Orgonico'), ('FC', 'Fibras de Coco'), ('B', 'Bambu')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='styles',
            field=models.CharField(choices=[('M', 'Minimalista'), ('MU', 'Multifuncionales'), ('S', 'Sostenibles'), ('I', 'Industrial')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='type',
            field=models.CharField(choices=[('H', 'Hool/Entrada'), ('A', 'Organizacion'), ('B', 'Confort')], max_length=30),
        ),
    ]
