# Generated by Django 4.2 on 2025-01-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0002_alter_mueble_material_alter_mueble_style_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_mueble',
            old_name='type',
            new_name='type_furniture',
        ),
    ]
