# Generated by Django 4.2 on 2025-02-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0002_alter_mueble_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('muebles_categoria', models.ManyToManyField(to='mueblesemae.mueble')),
            ],
        ),
    ]
