# Generated by Django 4.2 on 2025-01-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0003_rename_type_tipo_mueble_type_furniture'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tipo_mueble',
            constraint=models.CheckConstraint(check=models.Q(('type_furniture__in', ['O', 'H', 'C'])), name='check_types_furniture'),
        ),
    ]
