# Generated by Django 4.2 on 2025-01-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0003_alter_mueble_materials_alter_mueble_styles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='materials',
            field=models.CharField(choices=[('B', 'Bambu'), ('C', 'Corcho'), ('E', 'Eco-plasticos'), ('FC', 'Fibras de Coco'), ('LO', 'Lino Orgonico'), ('M', 'Madera Sostenible')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='styles',
            field=models.CharField(choices=[('MU', 'Multifuncionales'), ('I', 'Industrial'), ('S', 'Sostenibles'), ('M', 'Minimalista')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='type',
            field=models.CharField(choices=[('H', 'Hool/Entrada'), ('B', 'Confort'), ('A', 'Organizacion')], max_length=30),
        ),
    ]
