# Generated by Django 4.2 on 2025-02-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0004_remove_mueble_type_alter_categoria_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='type',
        ),
    ]
