# Generated by Django 4.2 on 2025-01-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0004_tipo_mueble_check_types_furniture'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tipo_mueble',
            name='check_types_furniture',
        ),
        migrations.AddConstraint(
            model_name='tipo_mueble',
            constraint=models.CheckConstraint(check=models.Q(('type_furniture__in', ['Organizacion', 'Hool', 'Confort'])), name='check_types_furniture'),
        ),
    ]
