# Generated by Django 4.2 on 2025-01-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mueblesemae', '0005_remove_tipo_mueble_check_types_furniture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_mueble',
            name='type_furniture',
            field=models.CharField(max_length=30),
        ),
    ]
